function operations_ = decodeNodes_(~, active, functionSet, genes, structure)
    operations_ = '';

    for i = 1:length(active)
        if active(i) <= max(structure.programInputs)
            operations_ = [ ...
                operations_, ...
                sprintf('\n'), ...
                'Node Index', ...
                num2str(active(i)), ...
                ' = input (', ...
                num2str(active(i)), ...
                ')' ...
            ];
        else
            operations_ = [ ...
                operations_, ...
                sprintf('\n'), ...
                'Computational Node', ...
                num2str(active(i) - max(structure.programInputs)), ...
                '=', ...
                functionSet(genes(structure.functionGenes(active(i) - max(structure.programInputs)))), ...
                '(', ...
                num2str(genes(structure.connectionGenes{1}(active(i) - max(structure.programInputs)))), ...
                ',', ...
                num2str(genes(structure.connectionGenes{2}(active(i) - max(structure.programInputs)))), ...
                ')' ...
            ];
        end
    end
end
