function fitness_ = compute(this, vararg)

    store = this.train_( ...
        vararg.config.sizes, ...
        vararg.config.structure, ...
        vararg.genes, ...
        vararg.activeNodes, ...
        vararg.programInputs, ...
        vararg.functionSet ...
    );

    fitness = this.fitnessFunction_( ...
        store.tp.total, ...
        store.tn.total, ...
        store.fp.total, ...
        store.fn.total ...
    );

    fitness_ = fitness.get();

    if ~isfield(this.store_.tp, 'values') || this.store_.fitness <= fitness_
        this.store_ = store;
        this.store_.fitness = fitness_;

        classifier_ = struct( ...
            'sizes', vararg.config.sizes, ...
            'structure', vararg.config.structure, ...
            'pitch', this.config_.signal.pitch, ...
            'genes', vararg.genes, ...
            'active', vararg.activeNodes, ...
            'inputs', vararg.programInputs, ...
            'functions', '', ...
            'run', vararg.run, ...
            'fitness', fitness_, ...
            'threshold', this.fittestThreshold_ ...
        );

        classifier_.functions = vararg.functionSet;

        save([this.config_.runs_directory, '/', num2str(vararg.run), '.mat'], 'classifier_');
    end
end
