function audio = test_(this, config)

    audio(floor(config.test_cases / 4), config.samples) = zeros();

    for e = 1:3:config.test_cases/4

        audio(e,:) = this.createTruthySignal_( ...
            config.fundamental_frequency, ...
            config.sampling_frequency, ...
            config.samples, ...
            'square' ...
        );

        if e + 1 <= config.test_cases / 4
            audio(e + 1,:) = this.createTruthySignal_( ...
                config.fundamental_frequency, ...
                config.sampling_frequency, ...
                config.samples, ...
                'triangular' ...
            );

            if e + 2 <= config.test_cases / 4
                audio(e + 2,:) = this.createTruthySignal_( ...
                    config.fundamental_frequency, ...
                    config.sampling_frequency, ...
                    config.samples, ...
                    'sinusoid' ...
                );
            end
        end
    end
end
