function audio = train_(this, config)
    audio(config.test_cases, config.samples) = zeros();

    for e = 1:3:config.test_cases

        if e <= config.test_cases / 2

            audio(e,:) = this.createTruthySignal_( ...
                config.fundamental_frequency, ...
                config.sampling_frequency, ...
                config.samples, ...
                'square' ...
            );

            if e + 1 <= config.test_cases / 2
                audio(e + 1,:) = this.createTruthySignal_( ...
                    config.fundamental_frequency, ...
                    config.sampling_frequency, ...
                    config.samples, ...
                    'triangular' ...
                );

                if e + 2 <= config.test_cases / 2
                    audio(e + 2,:) = this.createTruthySignal_( ...
                        config.fundamental_frequency, ...
                        config.sampling_frequency, ...
                        config.samples, ...
                        'sinusoid' ...
                    );
                else
                    audio(e + 2,:) = this.createFakeSignal_( ...
                        config.fundamental_frequency, ...
                        config.sampling_frequency, ...
                        config.samples, ...
                        'sinusoid' ...
                    );
                end
            else
                audio(e + 1,:) = this.createFakeSignal_( ...
                    config.fundamental_frequency, ...
                    config.sampling_frequency, ...
                    config.samples, ...
                    'triangular' ...
                );
            end

        else
            audio(e,:) = this.createFakeSignal_( ...
                config.fundamental_frequency, ...
                config.sampling_frequency, ...
                config.samples, ...
                'square' ...
            );

            if e + 1 <= config.test_cases
                audio(e + 1,:) = this.createFakeSignal_( ...
                    config.fundamental_frequency, ...
                    config.sampling_frequency, ...
                    config.samples, ...
                    'triangular' ...
                );

                if e + 2 <= config.test_cases / 2
                    audio(e + 2,:) = this.createFakeSignal_( ...
                        config.fundamental_frequency, ...
                        config.sampling_frequency, ...
                        config.samples, ...
                        'sinusoid' ...
                    );
                end
            end
        end
    end
end
