function initFundamentalFrequencyClass_(this)
    this.classes_.fundamental_frequency = FundamentalFrequencyReport ( ...
        this.config_.base_signal, ...
        this.config_.fundamental_frequency, ...
        this.config_.runs_directory ...
    );
end
