function initGenerationClass_(this)
    if ~isfield(this.classes_, 'generation')
        this.classes_.generation = GenerationReport( ...
            this.config_, ...
            this.fitness_ ...
        );
    end
end
